A lot of things have been changed in this commit, as I was without internet for two days. Renamed package-installer to installer. Improved the network lemonbar block by checking network connection and internet connection separately. Changed the default color in popup-spawner to background. Changed the color of git directories in the zsh prompt from orange to yellow for those who do not use 256 colors. Re-ordered the if statement in the dropbox lemonbar block to prevent unnecessary commands. Fixed wallpaper-monitor from not working when connected to LAN only. Added atom dotfiles to stow. Allowed popup-spawner to have a specified color. Changed update popup to use the new popup-spawner syntax. Fixed i3 media key binds. Added more options to the screenie script including upload to imgur. Added i3 binds for new screenie options. General grammar and inconsistency fixes.

diff --git a/bin/bin/screenie b/bin/bin/screenie
--- a/bin/bin/screenie
+++ b/bin/bin/screenie
@@ -1,8 +1,42 @@
 #!/bin/bash
 
-file='/tmp/screenie.png'
+# Configuration
+image="/tmp/screenie.png"
+clientID="3e7a4deb7ac67da"  # ID for imgur authentication.
 
-scrot -q 100 $file
+imgurUpload(){
+    # Upload image to imgur.
+    res=$(curl -sH "Authorization: Client-ID ${clientID}" -F "image=@${image}" "https://api.imgur.com/3/upload")
 
-TYPE=$(file -b --mime-type "$file")
-xclip -selection clipboard -t "$TYPE" < "$file"
+    # Store imgur link in clipboard.
+    echo ${res} | grep -qo '"status":200' && link=$(echo ${res} | sed -e 's/.*"link":"\([^"]*\).*/\1/' -e 's/\\//g')
+    test -n "${link}" && (printf ${link} | xclip; printf "\a") || echo "${res}" > "$image.error"
+}
+
+clipboard(){
+    # Check filetype of image in order to store in clipboard.
+    filetype=$(file -b --mime-type "${image}")
+
+    # Store image in clipboard
+    xclip -selection clipboard -t "${filetype}" < "${image}"
+}
+
+# Remove any previous image.
+rm ${image}
+
+# Parse arguments
+while getopts f:s:u:c: opt; do
+    case $opt in
+        f) scrot -z -q 100 ${image} ;;
+        s) scrot -z -q 100 -s ${image} ;;
+        u) $(imgurUpload) ;;
+        c) $(clipboard) ;;
+    esac
+done
+
+# Throw popup on success of screenshot.
+if [[ -e ${image} ]]; then
+    ~/.config/lemonbar/popup-spawner %green Screenshot was taken successfully.
+else
+    ~/.config/lemonbar/popup-spawner %red Screenshot failed.
+fi
